### ISSUE TITLE
JupyterLab from v2 to v3

### ISSUE THREAD

**Issue by learning4life** [SCiO-systems/cgspatial-notebook#10]
Support for the new [JupyterLab v3](https://blog.jupyter.org/jupyterlab-3-0-is-out-4f58385e25bb) (jupyter/datascience-notebook:lab-3.0.x) would be great!

**Comment by KyriakosZorbas** [comment]
Hello @learning4life , thank you for your comment. We expect to have this enhancement in mid March.

**Comment by sotkonstantinidis** [comment]
@learning4life support for JupyterLab v3 has been added! I am closing the issue.
