### ISSUE TITLE
Binder Link Not Working

### ISSUE THREAD

**Issue by BrettBoval** [SCiO-systems/cgspatial-notebook#5]
URL linked in the readme https://mybinder.org/v2/gh/SCiO-systems/cgspatial-notebook/master does not load.

This is what the build log says.

```shell
Waiting for build to start...
Picked Git content provider.
Cloning into '/tmp/repo2dockerbycmo_7r'...
HEAD is now at a61ce4a Update Dockerfile
Using DockerBuildPack builder
Error during build: 400 Client Error: Bad Request ("the Dockerfile (binder/Dockerfile) cannot be empty")
```

**Comment by KyriakosZorbas** [comment]
Hello Brett,

We managed to resolve the issue.
Please try again and let me know if you need something else
or you have any questions.

Best Regards,
Kyriakos Zorbas
