### ISSUE TITLE
install libraries for ciatlab instance

### ISSUE THREAD

**Issue by jramirezv** [SCiO-systems/cgspatial-notebook#6]
This is the (hopefully complete) list of libraries needed from us:

raster 
ggplot2 
dplyr 
ncdf4 
maptools 
rgdal 
cluster 
fastcluster 
tidyr 
foreach 
parallel 
doPararel  
tidyverse 
stringr 
velox 
glue 
pacman 
rgeos 
purrr 
fst 
sf 
future 
furrr 
lubridate 
vroom 
sp 
compiler 
tcltk 
AdehabitatHR 
Ggspatial 
doSNOW 
sdm 
dismo 
distances 
sp 
rlang  
gdistance 
caret 
earth 
FactoMineR 
deldir 
parallelDist 
bindrcpp 
pROC 
maxnet 
usdm 
tictoc 
snow 
gtools 
doMC 
ade4 
terra 
trend 
climatrends 
CaretEnsemble

All should be in CRAN. If there are spelling issues that lead to the package not being found please let me know. I also assume that some of these packages will have their own dependencies.

**Comment by KyriakosZorbas** [comment]
All the above libraries except terra have been added !!
